export enum RECOIL_ATOMS_KEYS {
  APPSTATE_PAGE                  = 'APPSTATE_PAGE',
  APPSTATE_USERLIST              = 'APPSTATE_USERLIST',
  APPSTATE_USERLIST_NOTAPP       = 'APPSTATE_USERLIST_NOTAPP',
  APPSTATE_USERLIST_UPLOAD       = 'APPSTATE_USERLIST_UPLOAD',
  APPSTATE_BADGELIST             = 'APPSTATE_BADGELIST',
  APPSTATE_BADGE_USERLIST        = 'APPSTATE_BADGE_USERLIST',
  APPSTATE_DIALOG                = 'APPSTATE_DIALOG',
}
