export enum RECOIL_ATOMS_KEYS {
  APPSTATE_SEL_HEADER            = 'APPSTATE_SEL_HEADER', 
  APPSTATE_SEL_PAGE              = 'APPSTATE_SEL_PAGE',
  APPSTATE_EVENT                 = 'APPSTATE_EVENT',
  APPSTATE_PAGE                  = 'APPSTATE_PAGE',
  APPSTATE_USERLIST              = 'APPSTATE_USERLIST',
  APPSTATE_USERLIST_NOTAPP       = 'APPSTATE_USERLIST_NOTAPP',
  APPSTATE_USERLIST_UPLOAD       = 'APPSTATE_USERLIST_UPLOAD',
  APPSTATE_BADGELIST             = 'APPSTATE_BADGELIST',
  APPSTATE_BADGE_USERLIST        = 'APPSTATE_BADGE_USERLIST',

  BADGE_LIST_STATE = "badgeListState",
  BADGE_DETAIL_STATE = "badgeDetailState",
  APP_STATE = "appState", 
}
